import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";



export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-gray-100"
      >
        {/* Navbar */}
        <nav className="bg-blue-600 p-4 sticky top-0 shadow-md">
          <ul className="flex space-x-8 text-white font-medium max-w-7xl mx-auto">
            <li>
              <Link href="/" className="hover:text-blue-200 transition-colors">
                Home
              </Link>
            </li>
            <li>
              <Link href="/expenses" className="hover:text-blue-200 transition-colors">
                Expenses
              </Link>
            </li>
            <li>
              <Link href="/about" className="hover:text-blue-200 transition-colors">
                About
              </Link>
            </li>
          </ul>
        </nav>
        {/* Page Content */}
        <main className="max-w-7xl mx-auto p-6">
          {children}
        </main>
      
      </body>
    </html>
  );
}
