import type { Metadata } from "next";

import "./globals.css";
import Link from "next/link";
import { auth, signOut } from "@/app/api/auth/[...nextauth]/route";
import { Session } from "next-auth";


export const metadata: Metadata = {
  title: "Expense Tracker",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: Session | null  = await auth();

  return (
    <html lang="en">
      <body
        className="bg-gray-100"
      >
        {/* Navbar */}
        <nav className="bg-blue-700 p-4 sticky top-0 shadow-md">
          <ul className="flex space-x-8 text-white font-medium max-w-7xl mx-auto">
            <li>
              <Link href="/" className="hover:text-blue-200 transition-colors">
                Home
              </Link>
            </li>
            <li>
              <Link href="/expenses" className="hover:text-blue-200 transition-colors">
                Expenses
              </Link>
            </li>
            <li>
              <Link href="/about" className="hover:text-blue-200 transition-colors">
                About
              </Link>
            </li>
            <li className="ml-auto">
              {session ? (
                <form
                  action={async () => {
                    "use server";
                    await signOut();
                  }}
                >
                  <button className="hover:text-blue-200 transition-colors">
                    Sign Out
                  </button>
                </form>
              ) : (
                <Link href="/signin" className="hover:text-blue-200 transition-colors">
                  Sign In
                </Link>
              )}
            </li>
          </ul>
        </nav>
        {/* Page Content */}
        <main className="max-w-7xl mx-auto p-6 pt-16">
          {children}
          
        </main>
        
      </body>
    </html>
  );
}
